FROM node:alpine
# Adding git to install packages from private repos
RUN apk --no-cache add git

# Install the application's dependencies into the node_modules's cache directory.
WORKDIR /app
COPY package.json .
COPY package-lock.json ./

COPY . .

ENTRYPOINT ["/bin/sh", "-c", "npm install && npm run dev"]

